
stages:
  - codegen
  - build
  - benchmark
  - package

codegen-job:
  tags:
    - matlab
  stage: codegen
  script:
    - "make asr.zip"
  artifacts:
    paths:
      - asr.zip

build-job:
  tags:
    - pi
  stage: build
  dependencies:
    - codegen-job
  script:
    - "unzip -o -d codegen asr.zip" 
    - "make asr"
  artifacts:
    paths:
      - asr.so

package-job:
  tags:
    - linux
  stage: package
  dependencies:
    - build-job
  script:
    - "make deb"
    
benchmark-job:
  tags:
    - pi
  stage: benchmark
  script:
    - "unzip -o asr.zip -d codegen"
    - "make benchmark"
    - "./benchmark --benchmark_out_format=console --benchmark_out=benchmark.log"
