
stages:
  - codegen
  - benchmark
  - test
  - package

codegen-job:
  tags:
    - matlab
  stage: codegen
  script:
    - "make asr.zip"
  artifacts:
    paths:
      - asr.zip

package-x86-job:
  tags:
    - x86
  stage: package
  script:
    - "make deb"
  artifacts:
    paths:
      - "asr_*_*.deb"

package-arm-job:
  tags:
    - arm
  stage: package
  script:
    - "make deb"
  artifacts:
    paths:
      - "asr_*_*.deb"

benchmark-arm-job:
  tags:
    - arm
  stage: benchmark
  script:
    - "unzip -o asr.zip -d codegen"
    - "touch codegen/.directory"
    - "make benchmark"
    - "ulimit -c unlimited"
    - "./benchmark --benchmark_out_format=console --benchmark_out=benchmark.log"
  artifacts:
    paths:
      - "benchmark.log"
      - "benchmark"

benchmark-x86-job:
  tags:
    - x86
  stage: benchmark
  script:
    - "unzip -o asr.zip -d codegen"
    - "touch codegen/.directory"
    - "make benchmark"
    - "ulimit -c unlimited"
    - "./benchmark --benchmark_out_format=console --benchmark_out=benchmark.log"
  artifacts:
    paths:
      - "benchmark.log"
      - "benchmark"

test-arm-job:
  tags:
    - arm
  stage: test
  script:
    - "unzip -o asr.zip -d codegen"
    - "touch codegen/.directory"
    - "make test"
    - "./test"

test-x86-job:
  tags:
    - x86
  stage: test
  script:
    - "unzip -o asr.zip -d codegen"
    - "touch codegen/.directory"
    - "make test"
    - "./test"
