# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/README.html#stages

stages:          # List of stages for jobs, and their order of execution
  - codegen
  - build
  - benchmark

codegen-job:
  tags:
    - matlab
  stage: codegen
  script:
    - "make asr.zip"
  artifacts:
    paths:
      - asr.zip

build-job:
  tags:
    - pi
  stage: build
  dependencies:
    - codegen-job
  script:
    - "unzip -o -d codegen asr.zip" 
    - "make asr"

benchmark-job:
  tags:
    - pi
  stage: benchmark
  script:
    - "unzip -o asr.zip -d codegen"
    - "make benchmark"
    - "./benchmark --benchmark_out_format=console --benchmark_out=benchmark.log"
